use task_1;
ALTER TABLE waterfalls_info ADD COLUMN distance int ;
ALTER TABLE waterfalls_info ADD COLUMN availability varchar(10);
ALTER TABLE waterfalls_info ADD COLUMN waterfalls_cost varchar(30);
ALTER TABLE waterfalls_info ADD COLUMN no_of_types int;
ALTER TABLE waterfalls_info ADD COLUMN investment int;
ALTER TABLE waterfalls_info ADD COLUMN waterfalls_info_types int;
ALTER TABLE waterfalls_info ADD COLUMN size varchar(10);
ALTER TABLE waterfalls_info ADD COLUMN  no_of_customers int;
ALTER TABLE waterfalls_info ADD COLUMN maintain varchar(50);
ALTER TABLE waterfalls_info ADD COLUMN largest_waterfalls  varchar(255);
DESC waterfalls_info;
ALTER TABLE waterfalls_info DROP COLUMN kms;
ALTER TABLE waterfalls_info DROP COLUMN speed;
DESC waterfalls_info;
ALTER TABLE waterfalls_info RENAME COLUMN waterfalls_info_types TO famous;
ALTER TABLE waterfalls_info RENAME COLUMN no_of_types TO no_of_people_visited;
ALTER TABLE waterfalls_info RENAME COLUMN state TO district;
ALTER TABLE waterfalls_info RENAME COLUMN availability TO waterfall_flows;
ALTER TABLE waterfalls_info RENAME COLUMN investment TO total_price;
DESC waterfalls_info;
ALTER TABLE waterfalls_info MODIFY famous varchar(20);
ALTER TABLE waterfalls_info MODIFY waterfalls_cost int;
ALTER TABLE waterfalls_info MODIFY size int;
DESC waterfalls_info;

use task_1;
ALTER TABLE vegetables ADD COLUMN types int ;
ALTER TABLE vegetables ADD COLUMN availability varchar(10);
ALTER TABLE vegetables ADD COLUMN vegetables_cost varchar(30);
ALTER TABLE vegetables ADD COLUMN no_of_types int;
ALTER TABLE vegetables ADD COLUMN investment int;
ALTER TABLE vegetables ADD COLUMN vegetables_types int;
ALTER TABLE vegetables ADD COLUMN size varchar(10);
ALTER TABLE vegetables ADD COLUMN  no_of_customers int;
ALTER TABLE vegetables ADD COLUMN seller varchar(50);
ALTER TABLE vegetables ADD COLUMN location  varchar(255);
DESC vegetables;
ALTER TABLE vegetables DROP COLUMN availability;
ALTER TABLE vegetables DROP COLUMN types;
DESC vegetables;
ALTER TABLE vegetables RENAME COLUMN vegetables_types TO new_shops;
ALTER TABLE vegetables RENAME COLUMN no_of_types TO types_info;
ALTER TABLE vegetables RENAME COLUMN location TO district;
ALTER TABLE vegetables RENAME COLUMN seller TO no_of_vegetables;
ALTER TABLE vegetables RENAME COLUMN investment TO total_price;
DESC vegetables;
ALTER TABLE vegetables MODIFY no_of_vegetables int;
ALTER TABLE vegetables MODIFY vegetables_cost int;
ALTER TABLE vegetables MODIFY district int;
DESC vegetables;


use task_1;
ALTER TABLE student ADD COLUMN subjects int ;
ALTER TABLE student ADD COLUMN fees int;
ALTER TABLE student ADD COLUMN exams_info varchar(30);
ALTER TABLE student ADD COLUMN types_of_sections int;
ALTER TABLE student ADD COLUMN investment int;
ALTER TABLE student ADD COLUMN classes int;
ALTER TABLE student ADD COLUMN size varchar(10);
ALTER TABLE student ADD COLUMN  no_of_students int;
ALTER TABLE student ADD COLUMN teachers varchar(50);
ALTER TABLE student ADD COLUMN school_bus  varchar(255);
DESC student;
ALTER TABLE student DROP COLUMN types_of_sections;
ALTER TABLE student DROP COLUMN fees;
DESC student;
ALTER TABLE student RENAME COLUMN teachers TO no_of_teachers;
ALTER TABLE student RENAME COLUMN subjects TO no_of_subjects;
ALTER TABLE student RENAME COLUMN city TO district;
ALTER TABLE student RENAME COLUMN school_name TO school_info;
ALTER TABLE student RENAME COLUMN investment TO total_price;
DESC student;
ALTER TABLE student MODIFY no_of_teachers int;
ALTER TABLE student MODIFY size int;
ALTER TABLE student MODIFY classes varchar(20);
DESC student;


use task_1;
ALTER TABLE mobile ADD COLUMN mobile_info int ;
ALTER TABLE mobile ADD COLUMN availability varchar(10);
ALTER TABLE mobile ADD COLUMN mobile_cost varchar(30);
ALTER TABLE mobile ADD COLUMN no_of_types int;
ALTER TABLE mobile ADD COLUMN investment int;
ALTER TABLE mobile ADD COLUMN mobile_types int;
ALTER TABLE mobile ADD COLUMN size varchar(10);
ALTER TABLE mobile ADD COLUMN  no_of_customers int;
ALTER TABLE mobile ADD COLUMN seller varchar(50);
ALTER TABLE mobile ADD COLUMN storage  varchar(255);
DESC mobile;
ALTER TABLE mobile DROP COLUMN seller;
ALTER TABLE mobile DROP COLUMN size;
DESC mobile;
ALTER TABLE mobile RENAME COLUMN mobile_types TO new_shops;
ALTER TABLE mobile RENAME COLUMN no_of_types TO types_info;
ALTER TABLE mobile RENAME COLUMN location TO district;
ALTER TABLE mobile RENAME COLUMN mall_info TO no_of_mobile;
ALTER TABLE mobile RENAME COLUMN investment TO total_price;
DESC mobile;
ALTER TABLE mobile MODIFY storage int;
ALTER TABLE mobile MODIFY mobile_cost int;
ALTER TABLE mobile MODIFY availability int;
DESC mobile;


use task_1;
ALTER TABLE malls ADD COLUMN mall_info int ;
ALTER TABLE malls ADD COLUMN availability varchar(10);
ALTER TABLE malls ADD COLUMN malls_cost varchar(30);
ALTER TABLE malls ADD COLUMN no_of_types int;
ALTER TABLE malls ADD COLUMN investment int;
ALTER TABLE malls ADD COLUMN malls_types int;
ALTER TABLE malls ADD COLUMN size varchar(10);
ALTER TABLE malls ADD COLUMN  no_of_customers int;
ALTER TABLE malls ADD COLUMN seller varchar(50);
ALTER TABLE malls ADD COLUMN things_info  varchar(255);
DESC malls;
ALTER TABLE malls DROP COLUMN seller;
ALTER TABLE malls DROP COLUMN size;
DESC malls;
ALTER TABLE malls RENAME COLUMN malls_types TO new_shops;
ALTER TABLE malls RENAME COLUMN no_of_types TO types_info;
ALTER TABLE malls RENAME COLUMN city TO district;
ALTER TABLE malls RENAME COLUMN mall_info TO no_of_malls;
ALTER TABLE malls RENAME COLUMN investment TO total_price;
DESC malls;
ALTER TABLE malls MODIFY no_of_malls int;
ALTER TABLE malls MODIFY malls_cost int;
ALTER TABLE malls MODIFY things_info int;
DESC malls;


use task_1;
ALTER TABLE fruits ADD COLUMN kg int;
ALTER TABLE fruits ADD COLUMN availability varchar(10);
ALTER TABLE fruits ADD COLUMN fruits_cost varchar(30);
ALTER TABLE fruits ADD COLUMN no_of_types int;
ALTER TABLE fruits ADD COLUMN fruits_taste varchar(30);
ALTER TABLE fruits ADD COLUMN fruits_types int;
ALTER TABLE fruits ADD COLUMN size varchar(10);
ALTER TABLE fruits ADD COLUMN import_place varchar(50);
ALTER TABLE fruits ADD COLUMN seller varchar(50);
ALTER TABLE fruits ADD COLUMN jack_fruits varchar(255);
DESC fruits;
ALTER TABLE fruits DROP COLUMN seller;
ALTER TABLE fruits DROP COLUMN jack_fruits;
DESC fruits;
ALTER TABLE fruits RENAME COLUMN race TO competition;
ALTER TABLE fruits RENAME COLUMN id_num TO fruits_number;
ALTER TABLE fruits RENAME COLUMN material TO red;
ALTER TABLE fruits RENAME COLUMN fruits_types TO benz;
ALTER TABLE fruits RENAME COLUMN city TO Banglore;
DESC fruits;
ALTER TABLE fruits MODIFY fruits_cost int;
ALTER TABLE fruits MODIFY size int;
ALTER TABLE fruits MODIFY fruits_cost int;
DESC fruits;

use task_1;
ALTER TABLE car ADD COLUMN weight int;
ALTER TABLE car ADD COLUMN availability varchar(10);
ALTER TABLE car ADD COLUMN car_cost varchar(30);
ALTER TABLE car ADD COLUMN year int;
ALTER TABLE car ADD COLUMN car_ride varchar(30);
ALTER TABLE car ADD COLUMN car_types int;
ALTER TABLE car ADD COLUMN size varchar(10);
ALTER TABLE car ADD COLUMN material varchar(50);
ALTER TABLE car ADD COLUMN car_type varchar(50);
ALTER TABLE car ADD COLUMN car_description varchar(255);
DESC car;
ALTER TABLE car DROP COLUMN size;
ALTER TABLE car DROP COLUMN weight;
DESC car;
ALTER TABLE car RENAME COLUMN race TO competition;
ALTER TABLE car RENAME COLUMN id_num TO car_number;
ALTER TABLE car RENAME COLUMN material TO red;
ALTER TABLE car RENAME COLUMN car_types TO benz;
ALTER TABLE car RENAME COLUMN city TO Banglore;
DESC car;
ALTER TABLE car MODIFY car_cost int;
ALTER TABLE car MODIFY car_ride int;
ALTER TABLE car MODIFY Banglore int;
DESC car;

use task_1;
ALTER TABLE busstand ADD COLUMN toilets int;
ALTER TABLE  busstand ADD COLUMN tiffin_centre varchar(10);
ALTER TABLE  busstand ADD COLUMN drivers_count varchar(30);
ALTER TABLE busstand  ADD COLUMN bus_numbers int;
ALTER TABLE busstand  ADD COLUMN  diesel int;
ALTER TABLE busstand  ADD COLUMN types int;
ALTER TABLE busstand ADD COLUMN no_of_seats int;
ALTER TABLE busstand ADD COLUMN head_of_busstand varchar(50);
ALTER TABLE busstand ADD COLUMN lights_in_busstand int;
ALTER TABLE busstand ADD COLUMN govt_name varchar(255);
DESC busstand;
ALTER TABLE busstand DROP COLUMN no_of_places;
ALTER TABLE busstand DROP COLUMN types;
DESC busstand;
ALTER TABLE busstand RENAME COLUMN govt_name TO Andhrapradesh;
ALTER TABLE busstand RENAME COLUMN district_name TO chittoor;
ALTER TABLE busstand RENAME COLUMN head_name TO sukumar;
ALTER TABLE busstand RENAME COLUMN no_of_buses TO buses_count;
ALTER TABLE busstand RENAME COLUMN tiffin_centre TO hotels_count;
DESC busstand;
ALTER TABLE busstand MODIFY hotels_count int;
ALTER TABLE busstand MODIFY drivers_count int;
ALTER TABLE busstand MODIFY  diesel varchar(20);
DESC busstand;

use task_1;
ALTER TABLE bike ADD COLUMN weight int;
ALTER TABLE bike ADD COLUMN availability varchar(10);
ALTER TABLE bike ADD COLUMN bike_cost varchar(30);
ALTER TABLE bike ADD COLUMN year int;
ALTER TABLE bike ADD COLUMN bike_ride varchar(30);
ALTER TABLE bike ADD COLUMN bike_types int;
ALTER TABLE bike ADD COLUMN size varchar(10);
ALTER TABLE bike ADD COLUMN material varchar(50);
ALTER TABLE bike ADD COLUMN bike_type varchar(50);
ALTER TABLE bike ADD COLUMN bike_description varchar(255);
DESC bike;
ALTER TABLE bike DROP COLUMN size;
ALTER TABLE bike DROP COLUMN weight;
DESC bike;
ALTER TABLE bike RENAME COLUMN speed TO race;
ALTER TABLE bike RENAME COLUMN wheels TO move;
ALTER TABLE bike RENAME COLUMN color TO black;
ALTER TABLE bike RENAME COLUMN bike_type TO scooty;
ALTER TABLE bike RENAME COLUMN num TO number_plate;
DESC bike;
ALTER TABLE bike MODIFY licenese int;
ALTER TABLE bike MODIFY milage int;
ALTER TABLE bike MODIFY bike_cost int;
DESC bike;

use task_1;
ALTER TABLE table1 ADD COLUMN info int;
ALTER TABLE table1 ADD COLUMN availability varchar(10);
ALTER TABLE table1 ADD COLUMN details varchar(30);
ALTER TABLE table1 ADD COLUMN year int;
ALTER TABLE table1 ADD COLUMN vehicles varchar(30);
ALTER TABLE table1 ADD COLUMN table1_types int;
ALTER TABLE table1 ADD COLUMN job varchar(10);
ALTER TABLE table1 ADD COLUMN inestment varchar(50);
ALTER TABLE table1 ADD COLUMN mail varchar(50);
ALTER TABLE table1 ADD COLUMN table1_description varchar(255);
DESC table1;
ALTER TABLE table1 DROP COLUMN job;
ALTER TABLE table1 DROP COLUMN weight;
DESC table1;
ALTER TABLE table1 RENAME COLUMN table1_types TO person_details;
ALTER TABLE table1 RENAME COLUMN mail TO mail_info;
ALTER TABLE table1 RENAME COLUMN details TO person_names;
ALTER TABLE table1 RENAME COLUMN info TO information;
ALTER TABLE table1 RENAME COLUMN year TO dateofbirth;
DESC table1;
ALTER TABLE table1 MODIFY vehicles int;
ALTER TABLE table1 MODIFY availability int;
ALTER TABLE table1 MODIFY person_details varchar(10);
DESC table1;








