use task_1;
SELECT * FROM bike;
ALTER TABLE bike DROP COLUMN race;
ALTER TABLE bike DROP COLUMN black;
ALTER TABLE bike DROP COLUMN move;
ALTER TABLE bike DROP COLUMN material;
ALTER TABLE bike DROP COLUMN scooty;
ALTER TABLE bike DROP COLUMN bike_description;
ALTER TABLE bike DROP COLUMN brand;
ALTER TABLE bike DROP COLUMN details;
ALTER TABLE bike DROP COLUMN licenese;
ALTER TABLE bike DROP COLUMN bike_ride;
ALTER TABLE bike DROP COLUMN bike_engine;
INSERT INTO bike VALUES(2,200000,1234,80,'Andhra Pradesh','yes',50000,2023,2,100);
INSERT INTO bike VALUES(3,300000,2234,70,'Telangana','No',30000,2022,8,500);
INSERT INTO bike VALUES(4,560000,3334,88,'Karnataka','yes',34000,2021,9,150);
INSERT INTO bike VALUES(5,770000,9008,55,'West bengal','No',50000,2023,2,120);
INSERT INTO bike VALUES(6,234000,9084,90,'Tamil nadu','No',12300,2012,12,130);
INSERT INTO bike VALUES(7,990000,2344,100,'Madhya Pradesh','yes',45600,2013,7,160);
INSERT INTO bike VALUES(8,780000,1114,120,'Maharastra','yes',67890,2017,6,300);
INSERT INTO bike VALUES(9,567000,1004,180,'kerala','No',65790,2018,4,550);
INSERT INTO bike VALUES(12,876000,1288,60,'Gujarat','yes',34567,2019,5,1000);
INSERT INTO bike VALUES(22,345000,1007,65,'Mumbai','No',12345,2020,21,1200);
SELECT * FROM bike where lights=2;
SELECT * FROM bike where price=234000;
SELECT * FROM bike where number_plate=2344;
SELECT * FROM bike where milage=120;
SELECT * FROM bike where bike_state='kerala';
SELECT * FROM bike where availability='yes';
SELECT * FROM bike where bike_cost=12345;
SELECT * FROM bike where year=2023;
SELECT * FROM bike where bike_types=9;
SELECT * FROM bike where weight=500;
DESC bike;

SELECT * FROM busstand;
ALTER TABLE busstand DROP COLUMN chittoor;
ALTER TABLE busstand DROP COLUMN sukumar;
ALTER TABLE busstand DROP COLUMN driver_names;
ALTER TABLE busstand DROP COLUMN min_speed;
ALTER TABLE busstand DROP COLUMN Andhrapradesh;
ALTER TABLE busstand DROP COLUMN tea_shops;
ALTER TABLE busstand DROP COLUMN toilets;
ALTER TABLE busstand DROP COLUMN hotels_count;
ALTER TABLE busstand DROP COLUMN diesel;
ALTER TABLE busstand DROP COLUMN no_of_shops;
ALTER TABLE busstand DROP COLUMN no_of_buses_eachroute;
ALTER TABLE busstand DROP COLUMN no_of_seats;
ALTER TABLE busstand DROP COLUMN lights_in_car;
INSERT INTO busstand VALUES(5,'Bhargavi',6,23,10,7,1000,500,'Raj',4);
INSERT INTO busstand VALUES(6,'Rani',4,23,11,9,200,340,'somu',3);
INSERT INTO busstand VALUES(15,'Seetha',5,22,11,1,300,650,'ramu',5);
INSERT INTO busstand VALUES(45,'Geetha',7,20,12,2,500,234,'kohli',6);
INSERT INTO busstand VALUES(52,'Suresh',8,23,13,3,600,789,'swamy',7);
INSERT INTO busstand VALUES(98,'Gamya',9,23,14,4,450,234,'ravi',9);
INSERT INTO busstand VALUES(23,'Ramya',11,23,15,5,230,456,'tony',12);
INSERT INTO busstand VALUES(25,'Sravani',12,23,16,6,560,908,'Ramesh',14);
INSERT INTO busstand VALUES(87,'Rangani',13,23,17,7,890,999,'vasu',54);
INSERT INTO busstand VALUES(8,'Thanmayi',16,23,18,8,110,235,'eshwar',49);

SELECT * FROM busstand where buses_count=5;
SELECT * FROM busstand where conductor_names='Rani';
SELECT * FROM busstand where count_express_buses=16;
SELECT * FROM busstand where no_of_shops=22;
SELECT * FROM busstand where teashops=15;
SELECT * FROM busstand where hotels_count=6;
SELECT * FROM busstand where no_of_drivers=500;
SELECT * FROM busstand where bus_numbers=789;
SELECT * FROM busstand where head_of_car='vasu';
SELECT * FROM busstand where hotels=9;


SELECT * FROM car;
ALTER TABLE car DROP COLUMN white;
ALTER TABLE car DROP COLUMN competition;
ALTER TABLE car DROP COLUMN new;
ALTER TABLE car DROP COLUMN no_of_wheels;
ALTER TABLE car DROP COLUMN Banglore;
ALTER TABLE car DROP COLUMN availability;
ALTER TABLE car DROP COLUMN car_ride;
ALTER TABLE car DROP COLUMN car_types;
ALTER TABLE car DROP COLUMN red;
ALTER TABLE car DROP COLUMN benz;
ALTER TABLE car DROP COLUMN details;
ALTER TABLE car DROP COLUMN instructions;
ALTER TABLE car DROP COLUMN no_of_seats;
INSERT INTO car VALUES(1243,300,234624,'Banglore',84222,2023);
INSERT INTO car VALUES(234.546,23555,'Btm',38498,2021);
INSERT INTO car VALUES(454,75,75754,'Marthahalli',74328,2018);
INSERT INTO car VALUES(434,355,34534,'Electronoc city',74233,2019);
INSERT INTO car VALUES(223,555,435346,'Silk Board',98633,2011);
INSERT INTO car VALUES(98,455,455355,'Hyderabad',28238,2021);
INSERT INTO car VALUES(23,'Ramya',11,23,15,5,230,456,'tony',12);
INSERT INTO car VALUES(25,'Sravani',12,23,16,6,560,908,'Ramesh',14);
INSERT INTO car VALUES(87,'Rangani',13,23,17,7,890,999,'vasu',54);
INSERT INTO car VALUES(8,'Thanmayi',16,23,18,8,110,235,'eshwar',49);

SELECT * FROM car where buses_count=5;
SELECT * FROM car where conductor_names='Rani';
SELECT * FROM car where count_express_buses=16;
SELECT * FROM car where no_of_shops=22;
SELECT * FROM car where teashops=15;
SELECT * FROM car where hotels_count=6;
SELECT * FROM car where no_of_drivers=500;
SELECT * FROM car where bus_numbers=789;
SELECT * FROM car where head_of_car='vasu';
SELECT * FROM car where hotels=9;

SELECT * FROM fruits;
ALTER TABLE fruits DROP COLUMN apple;
ALTER TABLE fruits DROP COLUMN orange;
ALTER TABLE fruits DROP COLUMN grapes;
ALTER TABLE fruits DROP COLUMN vendor;
ALTER TABLE fruits DROP COLUMN availability;
ALTER TABLE fruits DROP COLUMN fruits_taste;
ALTER TABLE fruits DROP COLUMN size;
ALTER TABLE fruits DROP COLUMN address;
ALTER TABLE fruits DROP COLUMN fruits_types;
ALTER TABLE fruits DROP COLUMN fruits_cost;
ALTER TABLE fruits DROP COLUMN city;
INSERT INTO fruits VALUES(300,23,'BTM','good',22,5,'Delhi');
INSERT INTO fruits VALUES(450,10,'KOlar','bad',12,5,'Kashmir');
INSERT INTO fruits VALUES(100,15,'chitoor','good',55,5,'Hyderabad');
INSERT INTO fruits VALUES(200,16,'Kanipakam','good',34,5,'Nizamabad');
INSERT INTO fruits VALUES(150,17,'Thirupathi','bad',20,5,'WestBnegal');
INSERT INTO fruits VALUES(250,13,'Vidya circle','bad',19,5,'Kolkata');
INSERT INTO fruits VALUES(460,18,'Majistic','good',22,78,'goa');
INSERT INTO fruits VALUES(123,19,'Airport road','bad',32,5,'coorg');
INSERT INTO fruits VALUES(326,20,'Silk board','good',23,5,'Bijapur');
INSERT INTO fruits VALUES(312,22,'Jaynagar','bad',22,12,'tamil nadu');
SELECT * FROM fruits where price=100;
SELECT * FROM fruits where weight=19;
SELECT * FROM fruits where location='Thirupathi';
SELECT * FROM fruits where taste='good';
SELECT * FROM fruits where kg=19;
SELECT * FROM fruits where no_of_types=5;
SELECT * FROM fruits where import_place='goa';
SELECT * FROM fruits where price=100;
SELECT * FROM fruits where price=100;


SELECT * FROM malls;
ALTER TABLE malls DROP COLUMN address;
ALTER TABLE malls DROP COLUMN brands;
ALTER TABLE malls DROP COLUMN availability;
ALTER TABLE malls DROP COLUMN malls_cost;
ALTER TABLE malls DROP COLUMN types_info;
ALTER TABLE malls DROP COLUMN investment;
ALTER TABLE malls DROP COLUMN new_shops;
ALTER TABLE malls DROP COLUMN things_info;
INSERT INTO malls (floors,mall_name,owner_name,no_of_shops,lights,price,district,no_of_customers,pincode,no_of_malls)VALUES
                (2,'lulu','Raju',40,1000,84374,'Thirupati',92874,517002,2),
                (3,'Trends','Haira',60,5000,11126,'Madanaplli',9089,510060,7),
                (4,'Max','Akash',50,200,36743,'kadapa',7892,5160030,9),
                (5,'Garuda','David',15,300,37484,'Nellore',2987,517142,8),
                (6,' UB City','Thomas',40,900,1235,'Hyderabad',890,536738,22),
                (7,'Mantri Square','Ramesh',54,230,97333,'Delhi',384,538733,3),
                (8,'FORUM','Vasu',12,980,9283,'agra',2533,387482,15),
                (9,'Banglore central mall','Nandu',34,133,3983,'Kerala',1333,517031,8),
                (11,'vega city mall','Bindu',18,352,35633,'Mysore',3313,510031,1);
SELECT * FROM malls WHERE floors=2;
SELECT * FROM malls WHERE mall_name='Trends';
SELECT * FROM malls WHERE owner_name='Akash';
SELECT * FROM malls WHERE no_of_shops=15;
SELECT * FROM malls WHERE lights=900;
SELECT * FROM malls WHERE price=97333;
SELECT * FROM malls WHERE district='agra';
SELECT * FROM malls WHERE pincode=517031;
SELECT * FROM malls WHERE no_of_malls=5;
SELECT * FROM malls WHERE no_of_customers=3313;

SELECT * FROM mobile;
ALTER TABLE mobile DROP COLUMN model_name;
ALTER TABLE mobile DROP COLUMN memory_ram;
ALTER TABLE mobile DROP COLUMN mobile_info;
ALTER TABLE mobile DROP COLUMN investment;
ALTER TABLE mobile DROP COLUMN new_shops;
ALTER TABLE mobile DROP COLUMN types_info;
ALTER TABLE mobile DROP COLUMN height;
ALTER TABLE mobile DROP COLUMN mobile_cost;
desc mobile;
INSERT INTO mobile VALUES(20000,'Black','Sangeetha','Banglore',12334,'OPPO',12,1,12,64);
INSERT INTO mobile VALUES(25000,'white','Celkon','Chittoor',764234,'vivo',13,0,14,128);
INSERT INTO mobile VALUES (30000,'Red','Cell 9','hyderbad',4234,'redmi',14,1,54,12);
INSERT INTO mobile VALUES  (70000,'Blue','Sangeetha','Thirupati',42455,'realme',15,0,34,64);
INSERT INTO mobile VALUES (65000,'Rainbow','Balaji','Mysore',85252,'samsung',16,1,90,128);
INSERT INTO mobile VALUES (55000,'white','Celkon','BTM',732469,'moto',17,1,23,12);
INSERT INTO mobile VALUES (18000,'Black','Vivo','Silk board',764712,'Nokia',18,0,24,32);
INSERT INTO mobile VALUES(15000,'Blue','Redmi store','Banglore',87474,'iphone',19,0,12,32);
INSERT INTO mobile VALUES (10000,'Red','croma','mysore',73687,'iq',20,1,11,128);
INSERT INTO mobile VALUES (79000,'Green','mi store','Mumbai',90843,'Redmi',21,0,49,6);
SELECT * FROM mobile WHERE price=10000;
SELECT * FROM malls WHERE color='red';
SELECT * FROM malls WHERE shop_name='Celkon';
SELECT * FROM mobile WHERE district='Chittoor';
SELECT * FROM mobile WHERE num=85252;
SELECT * FROM mobile WHERE brand='OPPO';
SELECT * FROM mobile WHERE mobile_info=21;
SELECT * FROM mobile WHERE availability=1;
SELECT * FROM mobile WHERE no_of_customers=24;
SELECT * FROM mobile WHERE storage=128;
                        
SELECT * FROM STUDENT;
ALTER TABLE student DROP COLUMN school_info;
ALTER TABLE student DROP COLUMN color;
ALTER TABLE student DROP COLUMN district;
ALTER TABLE student DROP COLUMN no_of_subjects;
ALTER TABLE student DROP COLUMN exams_info;
ALTER TABLE student DROP COLUMN classes;
ALTER TABLE student DROP COLUMN size;
ALTER TABLE student DROP COLUMN school_bus;
INSERT INTO student VALUES (10,6,'Banglore',20,4,90,'Raina',20000,10000,30);
INSERT INTO student VALUES (11,7,'HYderabad',30,5,32,'Tony',22200,12000,20);
INSERT INTO student VALUES (12,8,'Mysore',40,6,33,'suresh',21300,13000,10);
INSERT INTO student VALUES (9,5,'Thirupati',10,7,73,'ramesh',34500,13000,30);
INSERT INTO student VALUES (8,4,'manglore',15,8,12,'vasu',35500,14000,40);
INSERT INTO student VALUES (7,3,'BTM',20,9,22,'ganesh',35600,12400,32);
INSERT INTO student VALUES (6,2,'chittoor',25,4,47,'balaji',56400,18700,12);
INSERT INTO student VALUES (5,1,'delhi',22,2,56,'venkat',98740,11300,5);
INSERT INTO student VALUES (4,0,'Chennai',12,3,66,'mak',29750,20000,4);
INSERT INTO student VALUES (1,10,'Kerala',30,6,71,'sanju',292840,30000,8);
SELECT * from student where age=1;
SELECT * from student where class=0;
SELECT * from student where address='delhi';
SELECT * from student where weight=25;
SELECT * from student where height=9;
SELECT * from student where marks=32;
SELECT * from student where friend='vasu';
SELECT * from student where total_price=34500;
SELECT * from student where no_of_students=13000;
SELECT * from student where no_of_teachers=8;

SELECT * FROM table1;
ALTER TABLE table1 DROP COLUMN address;
ALTER TABLE table1 DROP COLUMN information;
ALTER TABLE table1 DROP COLUMN availability;
ALTER TABLE table1 DROP COLUMN person_names;
ALTER TABLE table1 DROP COLUMN dateofbirth;
ALTER TABLE table1 DROP COLUMN vehicles;
ALTER TABLE table1 DROP COLUMN city;
ALTER TABLE table1 DROP COLUMN person_details;
ALTER TABLE table1 DROP COLUMN inestment;
ALTER TABLE table1 DROP COLUMN table1_description;
ALTER TABLE table1 DROP COLUMN mall_info;
INSERT INTO table1 VALUES (1,'Sanjana','K','sanjana@gmail.com',4,90093732,'iiit','yes','student');
INSERT INTO table1 VALUES (2,'Thanu','c','thanu@gmail.com',5,470779,'svit','no','student');
INSERT INTO table1 VALUES (3,'Nandu','k c','nandu@gmail.com',7,08237,'iiit','yes','trainee');
INSERT INTO table1 VALUES (4,'Bindu','k c','bindu@gmail.com',8,81429,'vijayam','yes','employee');
INSERT INTO table1 VALUES (5,'Uzma','t','uzma@gmail.com',9,02844,'mysum','no','Trainee');
INSERT INTO table1 VALUES (6,'lahari','d','lahari7@gmail.com',10,98273,'svit','yes','trainee');
INSERT INTO table1 VALUES (7,'chandana','d','chandana8@gmail.com',11,98734,'svit','no','trainee');
INSERT INTO table1 VALUES (8,'poornima','j','pooornimaj@gmail.com',12,98338,'bijpaur','yes','trainee');
INSERT INTO table1 VALUES (9,'sahana','d','sahanad@gmail.com',13,98748,'mysore','no','student');
INSERT INTO table1 VALUES (10,'Rani','H','ranih@gmail.com',43,03984,'hassan','yes','teacher');
SELECT * from table1 where age=1;
SELECT * from table1 where class=0;
SELECT * from table1 where address='delhi';
SELECT * from table1 where weight=25;
SELECT * from table1 where height=9;
SELECT * from table1 where marks=32;
SELECT * from table1 where friend='vasu';
SELECT * from table1 where total_price=34500;
SELECT * from table1 where no_of_students=13000;
SELECT * from table1 where no_of_teachers=8;
SELECT * FROM vegetables;
desc vegetables;
ALTER TABLE vegetables DROP COLUMN tomato;
ALTER TABLE vegetables DROP COLUMN cabbage;
ALTER TABLE vegetables DROP COLUMN beans;
ALTER TABLE vegetables DROP COLUMN radish;
ALTER TABLE vegetables DROP COLUMN bendi;
ALTER TABLE vegetables DROP COLUMN shopkeper;
ALTER TABLE vegetables DROP COLUMN total_price;
ALTER TABLE vegetables DROP COLUMN size;
ALTER TABLE vegetables DROP COLUMN no_of_vegetables;
ALTER TABLE vegetables DROP COLUMN vegetable_shope_name;
ALTER TABLE vegetables DROP COLUMN types_info;
ALTER TABLE vegetables MODIFY COLUMN vegetable_shope_name varchar(20);
ALTER TABLE vegetables MODIFY COLUMN district varchar(20);

INSERT INTO vegetables VALUES (2,'yes',3,12,'Super market',76,2,44,'chittoor');
INSERT INTO vegetables VALUES (3,'No',5,50,'Vegetable store',90,5,23,'Banglore');
INSERT INTO vegetables VALUES (4,'no',9,38,'Lakshmi store',78,2,34,'Mysore');
INSERT INTO vegetables VALUES (5,'yes',4,65,'Maha lakshmi shop',56,9,67,'Thirupathi');
INSERT INTO vegetables VALUES (7,'yes',5,23,'Ram supermarket',33,8,36,'Marthahalli');
INSERT INTO vegetables VALUES (8,'yes',1,11,'Kanthi vegetables',22,1,5,'Madanapalli');
INSERT INTO vegetables VALUES (9,'no',6,10,'suraj store',77,3,54,'Hassan');
INSERT INTO vegetables VALUES (10,'no',19,18,'manglore market',35,7,35,'delhi');
INSERT INTO vegetables VALUES (1,'yes',10,12,'Chittoor market',30,17,34,'mumbai');
INSERT INTO vegetables VALUES (6,'no',11,13,'silk board market',20,27,41,'tamil nadu');
SELECT * from vegetables where count=1;
SELECT * from vegetables where cabbage='no';
SELECT * from vegetables where weight=3;
SELECT * from vegetables where price=50;
SELECT * from vegetables where vegetable_shope_name='Lakshmi store';
SELECT * from vegetables where count=5;
SELECT * from vegetables where vegetables_cost=20;
SELECT * from vegetables where new_shops=8;
SELECT * from vegetables where no_of_customers=67;
SELECT * from vegetables where district='chittoor';
SELECT * FROM waterfalls_info;
desc waterfalls_info;
ALTER TABLE waterfalls_info DROP COLUMN waterfalls_length;
ALTER TABLE waterfalls_info DROP COLUMN area;
ALTER TABLE waterfalls_info DROP COLUMN distance;
ALTER TABLE waterfalls_info DROP COLUMN waterfalls_description;
ALTER TABLE waterfalls_info DROP COLUMN largest_waterfalls;
ALTER TABLE waterfalls_info DROP COLUMN flow;
ALTER TABLE waterfalls_info DROP COLUMN address;
ALTER TABLE waterfalls_info DROP COLUMN district;
ALTER TABLE waterfalls_info DROP COLUMN waterfalls_info;
ALTER TABLE waterfalls_info DROP COLUMN maintain;
ALTER TABLE waterfalls_info DROP COLUMN waterfalls_info_cost;
ALTER TABLE waterfalls_info DROP COLUMN no_of_people_visited;
ALTER TABLE waterfalls_info DROP COLUMN entrance_price;
ALTER TABLE waterfalls_info DROP COLUMN famous;
ALTER TABLE waterfalls_info DROP COLUMN size;
ALTER TABLE waterfalls_info DROP COLUMN no_of_customers;
ALTER TABLE waterfalls_info MODIFY COLUMN waterfalls_area varchar(20);
INSERT INTO waterfalls_info VALUES (100,'Abbey falls','Banglore',1,'high',1000,5,10,'yes','Madikeri');
INSERT INTO waterfalls_info VALUES (200,' Mallalli Falls','Banglore',2,'speed',2000,4,56,'no','Kodagu');
INSERT INTO waterfalls_info VALUES (300,'Chunchi Fall','Mysore',3,'slow',200,3,12,'yes','Kanakapura Rural');
INSERT INTO waterfalls_info VALUES (400,'Dudhsagar Falls ','Banglore',4,'fast',300,5,32,'no','Mandya');
INSERT INTO waterfalls_info VALUES (500,' Hebbe Falls','Banglore',5,'slow',150,6,22,'yes','Chikkamagaluru');
INSERT INTO waterfalls_info VALUES (600,'Hogenakkal Falls','Banglore',6,'speed',210,31,20,'yes','Dharmapuri');
INSERT INTO waterfalls_info VALUES (700,'Iruppu Falls','Banglore',7,'slow',180,6,12,'no','Kodagu');
INSERT INTO waterfalls_info VALUES (800,'Chelavara Falls','Banglore',8,'high',140,8,14,'yes','Cheyyandane');
INSERT INTO waterfalls_info VALUES (900,'Shanti','Banglore',9,'average',170,9,17,'no','Chikmagalur');
INSERT INTO waterfalls_info VALUES (1000,'pykara falls','Banglore',10,'average',180,10,19,'yes','Pykara');
SELECT * from waterfalls_info where waterfalls_height=100;
SELECT * from waterfalls_info where waterfalls_name='Mallalli Falls';
SELECT * from waterfalls_info where location='Mysore';
SELECT * from waterfalls_info where no_of_waterfalls=4;
SELECT * from waterfalls_info where waterfall_flows='fast';
SELECT * from waterfalls_info where total_price=150;
SELECT * from waterfalls_info where visited_waterfalls=5;
SELECT * from waterfalls_info where waterfalls=20;
