use task_1;
SELECT * FROM busstand;
UPDATE busstand SET conductor_names='Nandu' WHERE buses_count=5;
UPDATE busstand SET count_express_buses=3 WHERE buses_count=8;
UPDATE busstand SET no_of_shops=21 WHERE buses_count=25;
UPDATE busstand SET head_of_busstand='raj' WHERE buses_count=45;
UPDATE busstand SET count_express_buses=12 WHERE buses_count=87;
DELETE FROM busstand WHERE buses_count=8;
DELETE FROM busstand WHERE buses_count=45;
DELETE FROM busstand WHERE buses_count=87;
DELETE FROM busstand WHERE buses_count=23;
DELETE FROM busstand WHERE buses_count=15;
SELECT * FROM car;
UPDATE car SET location='chennai' WHERE car_number=90;
UPDATE car SET distance=8933 WHERE car_number=83;
UPDATE car SET price=9837769 WHERE car_number=454;
UPDATE car SET location='KR puram' where car_number=234;
UPDATE car SET car_year=2018 WHERE car_number=13;
DELETE FROM car WHERE car_number=13;
DELETE FROM car WHERE car_number=90;
DELETE FROM car WHERE car_number=98;
DELETE FROM car WHERE car_number=434;
DELETE FROM car WHERE car_number=1243;
SELECT * FROM fruits;
UPDATE fruits SET  location='kanipakam' WHERE weight=15;
UPDATE fruits SET taste='good' WHERE price=123;
UPDATE fruits SET no_of_types=6 WHERE price=200;
UPDATE fruits SET import_place='chittoor' where price=326;
UPDATE fruits SET weight=29 WHERE price=312;
DELETE FROM fruits WHERE price=326 ;
DELETE FROM fruits WHERE price=123;
DELETE FROM fruits WHERE price=200;
DELETE FROM fruits WHERE price=312;
DELETE FROM fruits WHERE price=460;
SELECT * FROM malls;
UPDATE malls SET mall_name='central mall' WHERE floors=2 ;
UPDATE malls SET owner_name='Sravani' WHERE floors=3 ;
UPDATE malls SET  no_of_shops=89 WHERE floors=8;
UPDATE malls SET district='kanipakam' where floors=10;
UPDATE malls SET mall_name='trens mall' WHERE floors=4;
DELETE FROM malls WHERE floors=2;
DELETE FROM malls WHERE floors=3;
DELETE FROM malls WHERE floors=4;
DELETE FROM malls WHERE floors=5;
DELETE FROM malls WHERE floors=6;
SELECT * FROM mobile;
UPDATE mobile SET shop_name='oppo store' WHERE price=10000;
UPDATE mobile SET num=89474 WHERE price=18000;
UPDATE mobile SET color='blue'WHERE price=20000 ;
UPDATE mobile SET district='thirupati'where price=25000;
UPDATE mobile SET availability=1 WHERE price=30000;
DELETE FROM mobile WHERE price=10000;
DELETE FROM  mobile WHERE price=20000;
DELETE FROM mobile  WHERE price=79000;
DELETE FROM mobile WHERE price=80000;
DELETE FROM mobile WHERE price=18000;
SELECT * FROM student;
UPDATE student SET address='Goa' WHERE age=1;
UPDATE student SET weight=35 WHERE age=4;
UPDATE student SET height=87 WHERE age=8;
UPDATE student SET marks=100 where age=12;
UPDATE student SET friend='nandu' WHERE age=7 ;
DELETE FROM student WHERE age=1;
DELETE FROM student WHERE age=4;
DELETE FROM student WHERE age=5;
DELETE FROM student WHERE age=6;
DELETE FROM student WHERE age=15;
SELECT * FROM table1;
UPDATE table1 SET first_name='pooja' WHERE id_num=1;
UPDATE table1 SET last_name='k c' WHERE id_num=2;
UPDATE table1 SET height=28 WHERE id_num=6;
UPDATE table1 SET college_name='Vemu' where id_num=9;
UPDATE table1 SET mail_info='yes' WHERE id_num=9;
DELETE FROM table1 WHERE id_num=9;
DELETE FROM table1 WHERE id_num=6;
DELETE FROM table1 WHERE id_num=4;
DELETE FROM table1 WHERE id_num=7;
DELETE FROM table1 WHERE id_num=5;
SELECT * FROM vegetables;
UPDATE vegetables SET cabbage='yes' WHERE weight=5;
UPDATE vegetables SET price=150 WHERE district='Banglore';
UPDATE vegetables SET weight=6 WHERE count=6;
UPDATE vegetables SET no_of_customers=90 where price=65;
UPDATE vegetables SET new_shops=9 WHERE count=7;
DELETE FROM vegetables WHERE count=1;
DELETE FROM vegetables WHERE weight=9;
DELETE FROM vegetables WHERE cabbage='yes';
DELETE FROM vegetables WHERE vegetable_shope_name='Vegetable store';
DELETE FROM vegetables WHERE vegetables_cost=77;
SELECT * FROM table1;
UPDATE table1 SET first_name='pooja' WHERE id_num=1;
UPDATE table1 SET last_name='k c' WHERE id_num=2;
UPDATE table1 SET height=28 WHERE id_num=6;
UPDATE table1 SET college_name='Vemu' where id_num=9;
UPDATE table1 SET mail_info='yes' WHERE id_num=9;
DELETE FROM table1 WHERE id_num=9;
DELETE FROM table1 WHERE id_num=6;
DELETE FROM table1 WHERE id_num=4;
DELETE FROM table1 WHERE id_num=7;
DELETE FROM table1 WHERE id_num=5;