use task_1;
SELECT * FROM busstand;
UPDATE busstand SET conductor_names='Nandu' WHERE buses_count=5;
UPDATE busstand SET count_express_buses=3 WHERE buses_count=8;
UPDATE busstand SET no_of_shops=21 WHERE buses_count=25;
UPDATE busstand SET head_of_busstand='raj' WHERE buses_count=45;
UPDATE busstand SET count_express_buses=12 WHERE buses_count=87;
DELETE FROM busstand WHERE buses_count=8;
DELETE FROM busstand WHERE buses_count=45;
DELETE FROM busstand WHERE buses_count=87;
DELETE FROM busstand WHERE buses_count=23;
DELETE FROM busstand WHERE buses_count=15;
SELECT * FROM car;
UPDATE car SET location='chennai' WHERE car_number=90;
UPDATE car SET distance=8933 WHERE car_number=83;
UPDATE car SET price=9837769 WHERE car_number=454;
UPDATE car SET location='KR puram' where car_number=234;
UPDATE car SET car_year=2018 WHERE car_number=13;
DELETE FROM car WHERE car_number=13;
DELETE FROM car WHERE car_number=90;
DELETE FROM car WHERE car_number=98;
DELETE FROM car WHERE car_number=434;
DELETE FROM car WHERE car_number=1243;
SELECT * FROM fruits;
UPDATE fruits SET  location='kanipakam' WHERE weight=15;
UPDATE fruits SET taste='good' WHERE price=123;
UPDATE fruits SET no_of_types=6 WHERE price=200;
UPDATE fruits SET import_place='chittoor' where price=326;
UPDATE fruits SET weight=29 WHERE price=312;
DELETE FROM fruits WHERE price=326 ;
DELETE FROM fruits WHERE price=123;
DELETE FROM fruits WHERE price=200;
DELETE FROM fruits WHERE price=312;
DELETE FROM fruits WHERE price=460;
SELECT * FROM malls;
UPDATE malls SET mall_name='central mall' WHERE floors=2 ;
UPDATE malls SET owner_name='Sravani' WHERE floors=3 ;
UPDATE malls SET  no_of_shops=89 WHERE floors=8;
UPDATE malls SET district='kanipakam' where floors=10;
UPDATE malls SET mall_name='trens mall' WHERE floors=4;
DELETE FROM malls WHERE floors=2;
DELETE FROM malls WHERE floors=3;
DELETE FROM malls WHERE floors=4;
DELETE FROM malls WHERE floors=5;
DELETE FROM malls WHERE floors=6;
SELECT * FROM mobile;
UPDATE mobile SET shop_name='oppo store' WHERE price=10000;
UPDATE mobile SET num=89474 WHERE price=18000;
UPDATE mobile SET color='blue'WHERE price=20000 ;
UPDATE mobile SET district='thirupati'where price=25000;
UPDATE mobile SET availability=1 WHERE price=30000;
DELETE FROM mobile WHERE price=10000;
DELETE FROM  mobile WHERE price=20000;
DELETE FROM mobile  WHERE price=79000;
DELETE FROM mobile WHERE price=80000;
DELETE FROM mobile WHERE price=18000;
SELECT * FROM student;
UPDATE student SET address='Goa' WHERE age=1;
UPDATE student SET weight=35 WHERE age=4;
UPDATE student SET height=87 WHERE age=8;
UPDATE student SET marks=100 where age=12;
UPDATE student SET friend='nandu' WHERE age=7 ;
DELETE FROM student WHERE age=1;
DELETE FROM student WHERE age=4;
DELETE FROM student WHERE age=5;
DELETE FROM student WHERE age=6;
DELETE FROM student WHERE age=15;
SELECT * FROM table1;
UPDATE table1 SET first_name='pooja' WHERE id_num=1;
UPDATE table1 SET last_name='k c' WHERE id_num=2;
UPDATE table1 SET height=28 WHERE id_num=6;
UPDATE table1 SET college_name='Vemu' where id_num=9;
UPDATE table1 SET mail_info='yes' WHERE id_num=9;
DELETE FROM table1 WHERE id_num=9;
DELETE FROM table1 WHERE id_num=6;
DELETE FROM table1 WHERE id_num=4;
DELETE FROM table1 WHERE id_num=7;
DELETE FROM table1 WHERE id_num=5;
SELECT * FROM vegetables;
UPDATE vegetables SET cabbage='yes' WHERE weight=5;
UPDATE vegetables SET price=150 WHERE district='Banglore';
UPDATE vegetables SET weight=6 WHERE count=6;
UPDATE vegetables SET no_of_customers=90 where price=65;
UPDATE vegetables SET new_shops=9 WHERE count=7;
DELETE FROM vegetables WHERE count=1;
DELETE FROM vegetables WHERE weight=9;
DELETE FROM vegetables WHERE cabbage='yes';
DELETE FROM vegetables WHERE vegetable_shope_name='Vegetable store';
DELETE FROM vegetables WHERE vegetables_cost=77;
SELECT * FROM waterfalls_info;
UPDATE waterfalls_info SET waterfalls_name='Thalakona falls' WHERE no_of_waterfalls=4;
UPDATE waterfalls_info SET location='Hyderabad' WHERE total_price=300;
UPDATE waterfalls_info SET waterfalls=30 WHERE total_price=1000;
UPDATE waterfalls_info SET waterfalls_height=250 where waterfalls_name='Shanti';
UPDATE waterfalls_info SET availability='yes' WHERE waterfalls_area='Chikmagalur';
DELETE FROM waterfalls_info WHERE waterfalls=30;
DELETE FROM waterfalls_info WHERE waterfalls_name='Thalakona falls';
DELETE FROM waterfalls_info WHERE waterfalls_height=400;
DELETE FROM waterfalls_info WHERE no_of_waterfalls=8;
DELETE FROM waterfalls_info WHERE location='Hyderabad';
SELECT * FROM bike;
SELECT price,bike_state FROM bike where lights=2 AND year=2023;
SELECT milage,lights,year FROM bike where weight=500 AND bike_types=8;
SELECT bike_state FROM bike where availability='yes' AND year=2021;
SELECT * FROM bike where lights=5 AND number_plate=9008;
SELECT bike_cost,weight FROM bike where year=2017 AND milage=100;

SELECT price FROM bike where lights=2 OR year=2023;
SELECT price,milage,lights,year FROM bike where weight=500 OR bike_types=8 OR milage=70;
SELECT bike_state,bike_cost,milage FROM bike where bike_state='Andhra Pradesh'or availability='yes' OR year=2021;
SELECT * FROM bike where lights=5 OR number_plate=9008 OR price=200000;
SELECT bike_cost,weight,price FROM bike where year=2017 OR milage=80;

SELECT price,bike_state FROM bike where  lights IN(2,3,4) ;
SELECT * FROM bike where  bike_types IN(8,9,2);
SELECT bike_state,bike_cost FROM bike where  bike_cost in(50000,34000);
SELECT * FROM bike where lights IN(7,8,9);
SELECT bike_cost,weight FROM bike where year in(2023,2021);

SELECT price,bike_state FROM bike where  lights NOT IN(2,3,4) ;
SELECT * FROM bike where  bike_types NOT IN(8,9,2);
SELECT * FROM bike where  bike_cost NOT in(50000,34000);
SELECT * FROM bike where lights NOT IN(7,8,9);
SELECT *FROM bike where year NOT in(2023,2021);

SELECT price,bike_state FROM bike where  lights BETWEEN 3 AND 7 ;
SELECT * FROM bike where  milage BETWEEN 70 AND 200;
SELECT bike_state,bike_cost FROM bike where  bike_cost BETWEEN 30000 AND 70000;
SELECT * FROM bike where lights BETWEEN 1 AND 5;
SELECT bike_cost,weight FROM bike where year BETWEEN 2015 AND 2020;

SELECT * FROM car;
SELECT price,location FROM car where car_number=53 AND car_year=2001;
SELECT distance,car_year,car_number FROM car where location='Kerala' AND year=2000;
SELECT * FROM car where car_number=223 AND distance=555;
SELECT location,car_cost FROM car where location='Marathahalli' AND price=9837769;
SELECT * FROM car where car_year=2021 AND car_number=454;

SELECT price,location,car_cost FROM car where car_number=53 OR car_year=2001;
SELECT car_year,car_number FROM car where location='Delhi' OR year=2004;
SELECT * FROM car where car_number=223 OR distance=555;
SELECT location,car_cost FROM car where location='Marathahalli' OR price=9837769;
SELECT  location,car_year,car_numberFROM car where car_year=2021 OR car_number=454;

SELECT * FROM car where  car_number IN(83,234,454) ;
SELECT price FROM car where  car_year IN(2001,2004,2018,2021);
SELECT location,distance,car_year FROM car where  car_cost in(398332,74328);
SELECT * FROM car where car_number IN(53,223);
SELECT car_number FROM car where car_year in(2023,2021);

SELECT * FROM car where  car_number NOT IN(234,454) ;
SELECT price,car_year FROM car where  car_year NOT IN(2001,2021);
SELECT location,distance,car_year FROM car where  car_cost NOT in(398332,74328);
SELECT * FROM car where car_number NOT IN(53,223,83);
SELECT car_number,location FROM car where car_year NOT in(2023,2021);

SELECT * FROM car where car_number  BETWEEN 50 AND 200 ;
SELECT * FROM car where  distance BETWEEN 200 AND 500;
SELECT * FROM car where  car_cost BETWEEN 300000 AND 800000;
SELECT * FROM car where car_year BETWEEN 2000 AND 2010;
SELECT * FROM car where car_number BETWEEN 400 AND 1000;

select * from mobile;
SELECT price,color FROM mobile where color='white' AND no_of_customers=14;
SELECT * FROM mobile where shop_name='Celkon' AND availability=1;
SELECT district,num,brand FROM mobile where storage=64 AND availability=0;
SELECT * FROM mobile where brand='moto' AND price=55000;
SELECT shop_name,storage,color FROM mobile where color='Rainbow' AND mobile_info=16;

SELECT price,color FROM mobile where color='white' OR no_of_customers=14;
SELECT color,brand,district FROM mobile where shop_name='Celkon' OR availability=1;
SELECT district,num,brand FROM mobile where storage=64 OR availability=0;
SELECT * FROM mobile where brand='moto' OR price=55000;
SELECT shop_name,storage,color FROM mobile where color='Rainbow' OR mobile_info=16;

SELECT shop_name,color FROM mobile where  price IN(30000,65000) ;
SELECT brand,price,availability,storage FROM mobile where  storage IN(12,64,128);
SELECT mobile_info,district FROM mobile where  num in(4234);
SELECT * FROM mobile where storage IN(64,32);
SELECT * FROM mobile where mobile_info in(13,14,15);

SELECT * FROM mobile where storage NOT IN(64,32);
SELECT * FROM mobile where mobile_info NOT in(13,14,15);
SELECT shop_name,color FROM mobile where  price NOT IN(30000,65000) ;
SELECT brand,price,availability,storage FROM mobile where  storage NOT IN(12,64,128);
SELECT mobile_info,district FROM mobile where  num NOT in(4234);


SELECT * FROM mobile where price  BETWEEN 25000 AND 80000 ;
SELECT * FROM mobile where num  BETWEEN 2000 AND 700000;
SELECT * FROM mobile where  storage BETWEEN 12 AND 128;
SELECT * FROM mobile where no_of_customers BETWEEN 15 AND 50;
SELECT * FROM mobile where mobile_info BETWEEN 10 AND 15;

select * from student;
SELECT * FROM student where class=3 AND marks=22;
SELECT address,friend FROM student  where no_of_students=13000 AND friend='ramesh';
SELECT * FROM student where marks=100 AND address='Mysore';
SELECT friend,weight FROM student where age=9 AND total_price=91287;
SELECT class,total_price,height FROM student where no_of_teachers=40 AND marks=12 AND class=4;

SELECT friend,weight,height FROM student where class=3 OR marks=22;
SELECT class,address,friend FROM student  where no_of_students=13000 OR friend='ramesh';
SELECT * FROM student where marks=100 OR address='Mysore';
SELECT * FROM student where age=9 OR total_price=91287;
SELECT class,total_price,height FROM student where no_of_teachers=40 OR marks=12 OR class=4;

SELECT * FROM student where age  IN(7,8) ;
SELECT class,weight FROM student where class  IN(3,4,5,6);
SELECT age,class,marks FROM student where  height in(9,5,6,7);
SELECT * FROM student where no_of_students IN(12400,21300);
SELECT total_price,height FROM student where marks in(100,73,12,22);

SELECT * FROM student where age NOT IN(7,8) ;
SELECT class,weight FROM student where class NOT IN(3,4,5,6);
SELECT age,class,marks FROM student where  height NOT in(9,5,6,7);
SELECT * FROM student where no_of_students NOT IN(12400,21300);
SELECT total_price,height FROM student where marks NOT in(100,73,12,22);

SELECT * FROM student where age  BETWEEN 4 AND 15 ;
SELECT * FROM student where weight  BETWEEN 10 AND 50;
SELECT * FROM student where  marks BETWEEN 12 AND 128;
SELECT * FROM student where no_of_students BETWEEN 10000 AND 12000;
SELECT * FROM student where class BETWEEN 5 AND 15;